services:
  builder:
    stdin_open: true
    tty: true
    privileged: true
    image: "ghcr.io/pine64/openpinebuds:latest-sdk"
    build:
      context: .
    volumes:
      - ./:/usr/src:Z
      - /dev/:/dev/
